<?php
// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
$ch = curl_init();

curl_setopt($ch, CURLOPT_URL, 'https://multichannel.qiscus.com/whatsapp/v1/{{app_id}}/{{channel_id}}/messages');
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_POST, 1);
curl_setopt($ch, CURLOPT_POSTFIELDS, '{
    "to": "6281212962123",
    "type": "template",
    "template": {
        "namespace": "6616bb93_d895_41e7_8bbe_2c528219e56e",
        "name": "ticket_resolved_122",
        "language": {
            "policy": "deterministic",
            "code": "en"
        },
        "components": [
            {
                "type" : "header",
                "parameters": [
                    {
                        "type": "text",
                        "text": "John"
                    }
                ]
            },
            {
                "type" : "body",
                "parameters": [
                    {
                        "type": "text",
                        "text": "Ticket 001"
                    }
                ]
            }
        ]
    }
}');

$headers = array();
$headers[] = 'Qiscus-App-Id: cffec-nj2bfgqzntcojbq';
$headers[] = 'Qiscus-Secret-Key: e7321011619847f7741cb8ef1134c377';
$headers[] = 'Content-Type: application/json';
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

$result = curl_exec($ch);
if (curl_errno($ch)) {
    echo 'Error:' . curl_error($ch);
}
curl_close($ch);
?>